on: push
name: Publish Website Leandro Arturi
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      with:
        ftp-server: ftp://leandroarturi.com:21/
        ftp-username: u982958056.larturi
        ftp-password: ${{secrets.FTP_PASSWORD}}
