on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'root'
        server: '66.97.46.237:5972'
        ssh_private_key: ${{ secrets.FTP_PASSWORD }} 
        local_path: './static/*'
        remote_path: '/var/www/leandroarturi.com.ar/public_html/'
        args: '-o ConnectTimeout=5'